language: node_js
node_js:
  - '0.12'
before_script:
  - npm install grunt-cli -g
notifications:
  webhooks:
    urls:
      - http://fish.pencilcode.net/pull/staging
    on_success: always
    on_failure: never
    on_start: false
